### ISSUE TITLE
New config errors: report here!

### ISSUE THREAD

**Issue by bruvv** [buluba89/Yatcobot#16]
I get the following error with the new bot:
```confuse.ConfigTypeError: twitter.consumer_key: must be a string```

Although my consumer key is what is working with the older version of the bot

**Comment by buluba89** [comment]
Did you rename config.sample.yaml  to config.yaml and replace null with your api keys ?

**Comment by nivong** [comment]
That is a yes to both

**Comment by buluba89** [comment]
Try to pass your config explicitly with the --config argument

**Comment by buluba89** [comment]
Also how did you install? From github  repo or from pip?

**Comment by Tinismo** [comment]
Me, I got this
confuse.ConfigTypeError: twitter.search.filter.min_retweets.enabled: must be a bool, not str

**Comment by buluba89** [comment]
@Tinismo 
Can you share your config plz ? (remove the api keys of course !)

**Comment by Tinismo** [comment]
[config.zip](https://github.com/buluba89/Yatcobot/files/1865807/config.zip)

**Comment by Tinismo** [comment]
oh, I found the solution (enabled: true)

**Comment by buluba89** [comment]
@Tinismo 
You have an error in the config
it should be
```yaml
    filter:
      # Filter out tweets that have less retweets than `number`
      min_retweets:
        # If this filter method is enabled
        enabled: true
```
not enabled: enabled

Also you dont need to uncomment everything  in the config, you can just override the settings that you want

**Comment by Tinismo** [comment]
In the documentation, it's enabled: enabled, you have to change it https://github.com/buluba89/Yatcobot/blob/master/docs/config.rst

**Comment by buluba89** [comment]
Oh my bad! I will fix it

**Comment by nivong** [comment]
```
2018-04-01 21:18:20 - yatcobot.actions - WARNING - Experimental feature actions.follow.multiple is enabled.                        
2018-04-01 21:18:20 - yatcobot.actions - WARNING - Will follow every mentioned user in a post.                                     
2018-04-01 21:18:20 - yatcobot.actions - WARNING - If unwanted behavior is observed, please open an issue on github along with the 
post id!                                                                                                                           
2018-04-01 21:18:21 - yatcobot.bot - INFO - === SCANNING FOR NEW CONTESTS ===                                                      
2018-04-01 21:18:21 - yatcobot.scheduler - ERROR - Exception in scheduled task :scan_new_contests                                  
Traceback (most recent call last):                                                                                                 
  File "/script/v2/yatcobot/scheduler.py", line 65, in run_task                                                                    
    self.tasks[index].action()                                                                                                     
  File "/script/v2/yatcobot/bot.py", line 100, in scan_new_contests                                                                
    lang = search_query['lang']                                                                                                    
KeyError: 'lang'                                                                                                                   
2018-04-01 21:18:21 - yatcobot.bot - INFO - === CHECKING RETWEET QUEUE ===                                                         
2018-04-01 21:18:21 - yatcobot.bot - INFO - Queue length: 0
```

config:
```
  search:
    queries:
      - retweet en win:
        lang:nl:
      - rt en win:
        lang:nl:
      - follow en win:
        lang:nl:
      - volg en win:
        lang:nl:
      - Giveaway retweet:
        lang:nl:
    max_queue: 100
```

**Comment by buluba89** [comment]
@nivong 

remove trailing :  like this
``` yaml
  search:
    queries:
      - retweet en win:
        lang:nl
      - rt en win:
        lang:nl
      - follow en win:
        lang:nl
      - volg en win:
        lang:nl
      - Giveaway retweet:
        lang:nl
    max_queue: 100

```

**Comment by nivong** [comment]
@buluba89 just updated my post, if i do that I get:
Could not find the exxpected :

**Comment by buluba89** [comment]
@nivong 
yes i edited the answer, you are missing a space too

**Comment by nivong** [comment]
that was the issue, thanks! working now :)

**Comment by nivong** [comment]
Is there an option to get email notifications btw?

**Comment by buluba89** [comment]
@nivong 
No i thought you were implementing it :P 

I will add it to my todo list !

**Comment by nivong** [comment]
I had it for the v1 bot, will check tomorrow if i can just copy paste it and if it is working :)

**Comment by harminoff** [comment]
Hello. I'm trying to test out  --test-mail and getting the following error.

`2018-07-12 11:38:24 - yatcobot.config - INFO - 2: Path: pkg/config/config_default.yaml
2018-07-12 11:38:24 - yatcobot.cli - INFO - Configuration loaded
Traceback (most recent call last):
  File "yatcobot.py", line 4, in <module>
    main()
  File "C:\Users\user\Desktop\python\Yatcobot-master\yatcobot\cli.py", line 41, in main
    MailNotifier.from_config().test()
AttributeError: type object 'MailNotifier' has no attribute 'from_config'
PS C:\Users\user\Desktop\python\Yatcobot-master>`

Have mail in config.yaml as follows

` notifiers:
#  pushbullet:
#    enabled: false
#    token: my_pushbullet_token
 mail:
   enabled: true
   host: smtp.gmail.com
   port: 587
   tls: true
   username: emailfrom@gmail.com
   password: password
   recipient: emailto@gmail.com`

**Comment by buluba89** [comment]
@harminoff 
Thanks for reporting this bug.
I fixed it and should be working correctly now !

**Comment by harminoff** [comment]
Wow amazing response time!

I tried again and am now getting

`PS C:\Users\user\Desktop\python\Yatcobot-master> yatcobot --test-mail
2018-07-12 13:06:58 - yatcobot.cli - INFO - Loading configuration
2018-07-12 13:06:58 - yatcobot.config - INFO - Loading config files (From highest priority to lowest):
2018-07-12 13:06:58 - yatcobot.config - INFO - 0: Path: C:\Users\user\Desktop\python\Yatcobot-master\config.yaml
2018-07-12 13:06:58 - yatcobot.config - INFO - 1: Path: e:\programming\python\python36-32\lib\site-packages\yatcobot\config\config_default.yaml
2018-07-12 13:06:58 - yatcobot.config - INFO - 2: Path: pkg/config/config_default.yaml
2018-07-12 13:06:58 - yatcobot.cli - INFO - Configuration loaded
Traceback (most recent call last):
  File "e:\programming\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\programming\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\programming\python\Python36-32\Scripts\yatcobot.exe\__main__.py", line 9, in <module>
  File "e:\programming\python\python36-32\lib\site-packages\yatcobot\cli.py", line 41, in main
    MailNotifier.from_config().test()
AttributeError: type object 'MailNotifier' has no attribute 'from_config'`

**Comment by buluba89** [comment]
@harminoff 
did you update the package ? 
If you installed it through pip run
`
pip install Yatcobot --upgrade
`
If you cloned it run
`
git pull
`

**Comment by calvin2000001** [comment]
hello, I am getting this error. Any ideas?

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/TwitterAPI/TwitterAPI.py", line 137, in request
    proxies=self.proxies)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/blocks/ids.json?tweet_mode=extended (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107bfd9e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/Documents/Yatcobot-master/yatcobot/scheduler.py", line 65, in run_task
    self.tasks[index].action()
  File "/Users/xxx/Documents/Yatcobot-master/yatcobot/bot.py", line 101, in update_blocked_users
    for b in self.client.get_blocks():
  File "/Users/xxx/Documents/Yatcobot-master/yatcobot/client.py", line 145, in get_blocks
    return self._api_call('blocks/ids')['ids']
  File "/Users/xxx/Documents/Yatcobot-master/yatcobot/client.py", line 186, in _api_call
    response = self.api.request(request, parameters).json()
  File "/usr/local/lib/python3.7/site-packages/TwitterAPI/TwitterAPI.py", line 140, in request
    raise TwitterConnectionError(e)
TwitterAPI.TwitterError.TwitterConnectionError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/blocks/ids.json?tweet_mode=extended (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107bfd9e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
ERROR:yatcobot.scheduler:Exception in scheduled task :update_blocked_users
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

**Comment by rydlo98** [comment]
Hello, the bot has been working for me for the most part, however if I un-comment the lines for the keywords and users for the blacklist, I get the following error.
```
2019-11-11 17:54:46 - yatcobot.cli - INFO - Loading configuration
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/confuse.py", line 659, in load_yaml
    return yaml.load(f, Loader=Loader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/root/Yatcobot/config.yaml", line 34, column 17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yatcobot.py", line 4, in <module>
    main()
  File "/root/Yatcobot/yatcobot/cli.py", line 36, in main
    TwitterConfig.load(args.config)
  File "/root/Yatcobot/yatcobot/config/__init__.py", line 77, in load
    config.set_file(filename)
  File "/usr/local/lib/python3.6/dist-packages/confuse.py", line 861, in set_file
    self.set(ConfigSource(load_yaml(filename), filename))
  File "/usr/local/lib/python3.6/dist-packages/confuse.py", line 661, in load_yaml
    raise ConfigReadError(filename, exc)
confuse.ConfigReadError: file /root/Yatcobot/config.yaml could not be read: mapping values are not allowed here
  in "/root/Yatcobot/config.yaml", line 34, column 17
```

Any advice would be appreciated.
