### ISSUE TITLE
Twitter API changed?

### ISSUE THREAD

**Issue by Fot3k** [buluba89/Yatcobot#28]
Suddenly getting errors when running the bot when previously not had any issues, config is not changed. Has Twitter made some changes in the API which is causing this error?

> `2020-03-01 23:00:21 - yatcobot.bot - INFO - === CHECKING RETWEET QUEUE ===
> 2020-03-01 23:00:21 - yatcobot.bot - INFO - Queue length: 75
> 2020-03-01 23:00:22 - yatcobot.bot - INFO - Retweeting: 1233442268528480258 We have a new giveaway today thanks to @RatalaikaGames. To win #Knightin+ o..
> 2020-03-01 23:00:22 - yatcobot.client - ERROR - Twitter api error code:261 error:Application cannot perform write actions. Contact Twitter Platform Operations through https://support.twitter.com/forms/platform
> 2020-03-01 23:00:22 - yatcobot.client - ERROR - Error during twitter api call friendships/create (parameters: {'screen_name': 'TGGJustin', 'tweet_mode': 'extended'})
> 2020-03-01 23:00:22 - yatcobot.scheduler - ERROR - Exception in scheduled task :enter_contest
> Traceback (most recent call last):
>   File "C:\Yatcobot\yatcobot\scheduler.py", line 65, in run_task
>     self.tasks[index].action()
>   File "C:\Yatcobot\yatcobot\bot.py", line 84, in enter_contest
>     action.process(post)
>   File "C:\Yatcobot\yatcobot\plugins\actions.py", line 47, in process
>     self.follow(post)
>   File "C:\Yatcobot\yatcobot\plugins\actions.py", line 72, in follow
>     self.client.follow(post['user']['screen_name'])
>   File "C:\Yatcobot\yatcobot\client.py", line 136, in follow
>     return self._api_call('friendships/create', {'screen_name': username})
>   File "C:\Yatcobot\yatcobot\client.py", line 189, in _api_call
>     self._check_for_errors(response)
>   File "C:\Yatcobot\yatcobot\client.py", line 207, in _check_for_errors
>     raise TwitterClientException()
> yatcobot.client.TwitterClientException
> `

Thanks.

**Comment by Fot3k** [comment]
Sorry please ignore or delete this. My twitter dev app was restricted to read only for some reason. Created a new app and now working fine again.
